name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup keystore
      run: |
        KEYSTORE_DIR="${RUNNER_TEMP}/keystore/"
        KEYSTORE_FILE="${KEYSTORE_DIR}/keystore.jks"
        
        mkdir "${KEYSTORE_DIR}"
        echo "${KEYSTORE_FILE_BASE64}" | base64 -d > "${KEYSTORE_FILE}"
        
        echo > ./keystore.properties
        echo "storeFile=${KEYSTORE_FILE}" >> ./keystore.properties
        echo "storePassword=${KEYSTORE_PASSWORD}" >> ./keystore.properties
        echo "keyAlias=${KEY_ALIAS}" >> ./keystore.properties
        echo "keyPassword=${KEY_PASSWORD}" >> ./keystore.properties
      env:
        KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -PsignDebug=1 -PsignRelease=1

    - name: Upload outputs
      uses: actions/upload-artifact@v3.0.0
      with:
        name: AAWirelessGateway
        path: ./app/build/outputs/apk/
